'use client';

import { useState, useEffect } from 'react';
import { Plus, TrendingUp, TrendingDown, DollarSign, AlertCircle, FileDown, Trash2 } from 'lucide-react';
import { InvoiceModal } from '@/components/finance/invoice-modal';
import { createClient } from '@/lib/supabase/client';
import type { Invoice } from '@/types';

const KPI = ({ icon: Icon, label, value, color }: { icon: any; label: string; value: string; color: string }) => (
  <div className="bg-surface border border-border rounded-xl p-4">
    <div className="flex items-center gap-2 mb-2">
      <div className={`p-1.5 rounded-lg ${color}`}><Icon size={16} /></div>
      <p className="text-text-muted text-xs">{label}</p>
    </div>
    <p className="text-text-primary font-bold text-xl">{value}</p>
  </div>
);

const generateInvoiceNumber = () => {
  const dateStr = new Date().toISOString().slice(0,10).replace(/-/g,'');
  const rand = Math.floor(Math.random() * 900) + 100;
  return `INV-${dateStr}-${rand}`;
};

const exportInvoicePDF = (inv: Invoice & { invoice_number?: string }) => {
  const win = window.open('', '_blank');
  if (!win) return;
  const statusColor = inv.status === 'Paid' ? '#22c55e' : inv.status === 'Overdue' ? '#ef4444' : inv.status === 'Sent' ? '#60a5fa' : '#6b7280';
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Invoice ${inv.invoice_number || ''}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; background: #fff; color: #1a1a1a; padding: 48px; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 48px; }
        .brand { font-size: 28px; font-weight: 800; color: #0d9488; letter-spacing: -0.5px; }
        .brand span { color: #1a1a1a; }
        .inv-meta { text-align: right; }
        .inv-number { font-size: 14px; color: #6b7280; }
        .inv-number strong { font-size: 18px; color: #1a1a1a; display: block; margin-bottom: 4px; }
        .status-badge { display: inline-block; padding: 4px 12px; border-radius: 999px; font-size: 12px; font-weight: 600; background: ${statusColor}1a; color: ${statusColor}; border: 1px solid ${statusColor}40; margin-top: 8px; }
        .section { margin-bottom: 32px; }
        .section-title { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #9ca3af; margin-bottom: 8px; }
        .client-name { font-size: 22px; font-weight: 700; color: #1a1a1a; }
        .description { font-size: 14px; color: #6b7280; margin-top: 4px; }
        .details-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 24px; margin-bottom: 32px; }
        .detail-box { background: #f9fafb; border-radius: 8px; padding: 16px; }
        .detail-label { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #9ca3af; margin-bottom: 4px; }
        .detail-value { font-size: 15px; font-weight: 600; color: #1a1a1a; }
        .amount-box { background: #f0fdfa; border: 1px solid #99f6e4; border-radius: 12px; padding: 24px 32px; display: flex; justify-content: space-between; align-items: center; margin-bottom: 48px; }
        .amount-label { font-size: 14px; color: #0f766e; font-weight: 500; }
        .amount-value { font-size: 36px; font-weight: 800; color: #0d9488; }
        .footer { text-align: center; font-size: 12px; color: #d1d5db; padding-top: 32px; border-top: 1px solid #f3f4f6; }
        @media print { body { padding: 32px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="brand">Festo<span>web</span></div>
          <div style="font-size:13px;color:#6b7280;margin-top:4px;">festoweb-crm.vercel.app</div>
        </div>
        <div class="inv-meta">
          <div class="inv-number"><strong>${inv.invoice_number || 'N/A'}</strong>Invoice Number</div>
          <span class="status-badge">${inv.status}</span>
        </div>
      </div>
      <div class="section">
        <div class="section-title">Billed To</div>
        <div class="client-name">${inv.client_name}</div>
        ${inv.description ? `<div class="description">${inv.description}</div>` : ''}
      </div>
      <div class="details-grid">
        <div class="detail-box"><div class="detail-label">Invoice Date</div><div class="detail-value">${inv.date || '—'}</div></div>
        <div class="detail-box"><div class="detail-label">Due Date</div><div class="detail-value">${inv.due_date || '—'}</div></div>
        <div class="detail-box"><div class="detail-label">Type</div><div class="detail-value" style="text-transform:capitalize;">${inv.type}</div></div>
      </div>
      <div class="amount-box">
        <div class="amount-label">Total Amount Due</div>
        <div class="amount-value">SAR ${(inv.amount || 0).toLocaleString()}</div>
      </div>
      <div class="footer">Generated by Festoweb CRM &nbsp;·&nbsp; ${new Date().toLocaleDateString('en-GB')}</div>
      <script>window.onload = () => { window.print(); }<\/script>
    </body>
    </html>
  `);
  win.document.close();
};

export default function FinancePage() {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [showModal, setShowModal] = useState(false);
  const [editingInvoice, setEditingInvoice] = useState<Invoice | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);

  const supabase = createClient();

  const fetchInvoices = async () => {
    setLoading(true);
    const { data, error: err } = await supabase
      .from('invoices')
      .select('*')
      .order('created_at', { ascending: false });
    if (err) setError(err.message);
    else if (data) setInvoices(data as Invoice[]);
    setLoading(false);
  };

  useEffect(() => { fetchInvoices(); }, []);

  const income   = invoices.filter(i => i.type === 'income' && i.status === 'Paid').reduce((s, i) => s + (i.amount || 0), 0);
  const pending  = invoices.filter(i => i.type === 'income' && i.status === 'Sent').reduce((s, i) => s + (i.amount || 0), 0);
  const expenses = invoices.filter(i => i.type === 'expense').reduce((s, i) => s + (i.amount || 0), 0);
  const overdue  = invoices.filter(i => i.status === 'Overdue').length;

  const handleSave = async (inv: Invoice) => {
    const payload = {
      client_name: inv.client_name,
      amount: inv.amount,
      type: inv.type,
      status: inv.status,
      description: inv.description,
      date: inv.date || new Date().toISOString().split('T')[0],
      due_date: inv.due_date || null,
      updated_at: new Date().toISOString(),
    };
    if (editingInvoice) {
      const { error: err } = await supabase.from('invoices').update(payload).eq('id', inv.id);
      if (err) { setError(err.message); return; }
    } else {
      const { error: err } = await supabase.from('invoices').insert([{
        ...payload,
        invoice_number: generateInvoiceNumber(),
        created_at: new Date().toISOString(),
      }]);
      if (err) { setError(err.message); return; }
    }
    setError(null);
    setShowModal(false);
    setEditingInvoice(null);
    fetchInvoices();
  };

  const handleDelete = async (id: string) => {
    setDeletingId(id);
    const { error: err } = await supabase.from('invoices').delete().eq('id', id);
    if (err) setError(err.message);
    else setInvoices(prev => prev.filter(i => i.id !== id));
    setDeletingId(null);
    setConfirmDeleteId(null);
  };

  const statusColors: Record<string, string> = {
    Paid: 'bg-accent/10 text-accent',
    Sent: 'bg-blue-400/10 text-blue-400',
    Draft: 'bg-surface-dynamic text-text-muted',
    Overdue: 'bg-red-400/10 text-red-400',
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-text-primary">Finance</h1>
          <p className="text-text-muted text-sm mt-1">Invoices, income & expenses</p>
        </div>
        <button
          onClick={() => { setEditingInvoice(null); setShowModal(true); }}
          className="flex items-center gap-2 bg-primary hover:bg-primary-hover text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors"
        >
          <Plus size={16} /> Add Invoice
        </button>
      </div>

      {error && (
        <div className="bg-red-500/10 border border-red-500/30 text-red-400 text-sm px-4 py-3 rounded-lg">
          ⚠️ Error: {error}
        </div>
      )}

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <KPI icon={TrendingUp}   label="Income Received" value={`SAR ${income.toLocaleString()}`}   color="bg-accent/10 text-accent" />
        <KPI icon={DollarSign}   label="Pending (Sent)"  value={`SAR ${pending.toLocaleString()}`}  color="bg-blue-400/10 text-blue-400" />
        <KPI icon={TrendingDown} label="Expenses"        value={`SAR ${expenses.toLocaleString()}`} color="bg-red-400/10 text-red-400" />
        <KPI icon={AlertCircle}  label="Overdue"         value={`${overdue} invoices`}               color="bg-orange-400/10 text-orange-400" />
      </div>

      <div className="bg-surface border border-border rounded-xl overflow-hidden">
        <div className="p-4 border-b border-border">
          <p className="text-text-primary font-semibold">All Transactions</p>
        </div>
        {loading ? (
          <div className="text-center py-12"><p className="text-text-muted text-sm">Loading...</p></div>
        ) : invoices.length === 0 ? (
          <div className="text-center py-12">
            <p className="text-text-muted text-sm">No transactions yet</p>
            <button onClick={() => { setEditingInvoice(null); setShowModal(true); }} className="mt-2 text-primary text-sm hover:underline">Add your first invoice</button>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-border">
                  {['#', 'Client / Description', 'Type', 'Amount', 'Status', 'Date', 'Due Date', ''].map(h => (
                    <th key={h} className="text-left text-text-faint text-xs font-medium px-4 py-3">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {invoices.map(inv => (
                  <tr key={inv.id} className="border-b border-border/50 hover:bg-surface2 transition-colors">
                    <td className="px-4 py-3 text-text-faint text-xs tabular-nums">{(inv as any).invoice_number}</td>
                    <td className="px-4 py-3">
                      <p className="text-text-primary text-sm font-medium">{inv.client_name}</p>
                      <p className="text-text-faint text-xs">{inv.description}</p>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`text-xs px-2 py-1 rounded-full ${inv.type === 'income' ? 'bg-accent/10 text-accent' : 'bg-red-400/10 text-red-400'}`}>{inv.type}</span>
                    </td>
                    <td className="px-4 py-3 text-text-primary text-sm font-semibold tabular-nums">SAR {(inv.amount || 0).toLocaleString()}</td>
                    <td className="px-4 py-3"><span className={`text-xs px-2 py-1 rounded-full ${statusColors[inv.status] || ''}`}>{inv.status}</span></td>
                    <td className="px-4 py-3 text-text-muted text-sm">{inv.date}</td>
                    <td className="px-4 py-3 text-text-muted text-sm">{inv.due_date || '—'}</td>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-3">
                        <button
                          onClick={() => exportInvoicePDF(inv as any)}
                          className="flex items-center gap-1 text-text-faint hover:text-primary text-xs transition-colors"
                          title="Export PDF"
                        >
                          <FileDown size={13} /> PDF
                        </button>
                        <button
                          onClick={() => { setEditingInvoice(inv); setShowModal(true); }}
                          className="text-text-faint hover:text-primary text-xs transition-colors"
                        >
                          Edit
                        </button>
                        {confirmDeleteId === inv.id ? (
                          <span className="flex items-center gap-1">
                            <button
                              onClick={() => handleDelete(inv.id)}
                              disabled={deletingId === inv.id}
                              className="text-red-400 hover:text-red-500 text-xs font-semibold transition-colors disabled:opacity-50"
                            >
                              {deletingId === inv.id ? 'Deleting...' : 'Confirm'}
                            </button>
                            <button
                              onClick={() => setConfirmDeleteId(null)}
                              className="text-text-faint hover:text-text-muted text-xs transition-colors ml-1"
                            >
                              Cancel
                            </button>
                          </span>
                        ) : (
                          <button
                            onClick={() => setConfirmDeleteId(inv.id)}
                            className="text-text-faint hover:text-red-400 text-xs transition-colors"
                            title="Delete invoice"
                          >
                            <Trash2 size={13} />
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {showModal && <InvoiceModal invoice={editingInvoice} onSave={handleSave} onClose={() => { setShowModal(false); setEditingInvoice(null); }} />}
    </div>
  );
}
